/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppArrowBtns: typeof import('./../src/components/AppArrowBtns.vue')['default']
    AppSectionButton: typeof import('./../src/components/AppSectionButton.vue')['default']
    CategoriesCard: typeof import('./../src/components/CategoriesCard.vue')['default']
    ClientFeedbackCard: typeof import('../src/components/FeedbackCard.vue')['default']
    DestinationCard: typeof import('../src/components/ExpirienceCard.vue')['default']
    ExpirienceCard: typeof import('./../src/components/ExpirienceCard.vue')['default']
    FeedbackCard: typeof import('./../src/components/FeedbackCard.vue')['default']
    IconArrowLeft: typeof import('./../src/components/icons/icons-for-buttons/IconArrowLeft.vue')['default']
    IconArrowRight: typeof import('./../src/components/icons/icons-for-buttons/IconArrowRight.vue')['default']
    IconBooking: typeof import('./../src/components/icons/icons-for-buttons/IconBooking.vue')['default']
    IconCalendar: typeof import('./../src/components/icons/IconCalendar.vue')['default']
    IconFacebook: typeof import('./../src/components/icons/icons-social-medias/IconFacebook.vue')['default']
    IconFaceBook: typeof import('../src/components/icons/icons-social-medias/IconFacebook.vue')['default']
    IconInstagram: typeof import('./../src/components/icons/icons-social-medias/IconInstagram.vue')['default']
    IconMagnifyingGlass: typeof import('./../src/components/icons/icons-for-buttons/IconMagnifyingGlass.vue')['default']
    IconMenu: typeof import('./../src/components/icons/IconMenu.vue')['default']
    IconPoint: typeof import('./../src/components/icons/IconPoint.vue')['default']
    IconStar: typeof import('./../src/components/icons/IconStar.vue')['default']
    IconTwitter: typeof import('./../src/components/icons/icons-social-medias/IconTwitter.vue')['default']
    NavBar: typeof import('./../src/compone../src/components/ExpirienceCard.vue
    PopularDestinationCard: typeof import('./../src/components/PopularDestinationCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopDestinationCard: typeof import('./../src/components/TopDestinationCard.vue')['default']
    TourCard: typeof import('./../src/components/TourCard.vue')['default']
  }
}
