/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./../src/components/AppButton.vue')['default']
    AppInput: typeof import('./../src/components/AppInput.vue')['default']
    AppMultipleSelect: typeof import('./../src/components/AppMultipleSelect.vue')['default']
    Card: typeof import('./../src/components/Card.vue')['default']
    ContactItem: typeof import('./../src/views/contacts/components/ContactItem.vue')['default']
    DepartmentJobs: typeof import('./../src/views/job-openings/components/job-openings-list/DepartmentJobs.vue')['default']
    IconArrowForward: typeof import('./../src/components/icons/IconArrowForward.vue')['default']
    IconArrowRight: typeof import('./../src/components/icons/IconArrowRight.vue')['default']
    IconCheckMark: typeof import('./../src/components/icons/IconCheckMark.vue')['default']
    IconDropdown: typeof import('./../src/components/icons/IconDropdown.vue')['default']
    IconEnvelope: typeof import('./../src/components/icons/IconEnvelope.vue')['default']
    IconInfo: typeof import('./../src/components/icons/IconInfo.vue')['default']
    IconKeyboardUp: typeof import('./../src/components/icons/IconKeyboardUp.vue')['default']
    IconPhone: typeof import('./../src/components/icons/IconPhone.vue')['default']
    IconPlus: typeof import('./../src/components/icons/IconPlus.vue')['default']
    IconX: typeof import('./../src/components/icons/IconX.vue')['default']
    ItemObserver: typeof import('./../src/components/ItemObserver.vue')['default']
    JobOpeningsList: typeof import('./../src/views/job-openings/components/job-openings-list/JobOpeningsList.vue')['default']
    MenuList: typeof import('./../src/components/MenuList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
