<template>
  <svg
    id="Editable-line"
    width="64px"
    height="64px"
    viewBox="0 0 32 32"
    enable-background="new 0 0 32 32"
    version="1.1"
    xml:space="preserve"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    fill="#ffffff"
    stroke="#ffffff"
  >
    <g id="SVGRepo_bgCarrier" stroke-width="0" />
    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" />
    <g id="SVGRepo_iconCarrier">
      <line
        id="XMLID_103_"
        fill="none"
        stroke="#000000"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="2"
        x1="7"
        x2="25"
        y1="16"
        y2="16"
      />
      <line
        id="XMLID_102_"
        fill="none"
        stroke="#000000"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="2"
        x1="7"
        x2="25"
        y1="25"
        y2="25"
      />
      <line
        id="XMLID_101_"
        fill="none"
        stroke="#000000"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        stroke-width="2"
        x1="7"
        x2="25"
        y1="7"
        y2="7"
      />
    </g>
  </svg>
</template>
